#!/data/data/com.termux/files/usr/bin/bash
export U=$PREFIX/../ubuntu
log=$U/dpkg/log
echo $(date +"%H:%M:%S") $@ >> $log

function udpkg {
dpkg --admindir=$U/dpkg --instdir=$U $@
}

case "$1" in
"setup")
	udpkg --add-architecture arm64
	cp ld.so* $PREFIX/glibc/etc/
	# cp usr-ld.so.preload $PREFIX/etc/ld.so.preload
	exit 0;;
"clean")
	rm ld.so* $PREFIX/glibc/etc/
	exit 0;;
"test")
	shift
	udpkg $@
	exit 0;;
esac

fd=1
for a in $@; do
case "$a" in
	"--configure") action+=$a;;
"--pending") action+=$a;;
"--recursive") action+=$a;;
"--status-fd") fd=$2;;
"--unpack") action+=$a;;
esac
done

function install {
	for p in $@; do
		if [[ "$p" != *.deb ]]; then continue; fi
		name=$(dpkg -I $p|grep Package|cut -f3 -d" ")
		echo unpacking $fd $name $p | tee -a $log
		dpkg -x $p $U
		echo >> $U/dpkg/status
		dpkg -I $p |sed -n '/Package:/,$p'|cut -c2- >> $U/dpkg/status
		echo "Status: install ok installed" >> $U/dpkg/status
		echo "status $name:arm64: unpacked" >&$fd
done
}

case "$action" in
	"--configure--pending")
		echo skipping --configure | tee -a $log
		# echo "status $name:arm64: installed" >&$fd
		# sed -i s,"Status: install".*,"Status: install ok installed", $U/dpkg/status
	exit 0
	;;

	"--unpack--recursive")
		folder=$(echo $@|awk '{print $NF}')
		for f in $(ls $folder); do
		echo $f
		install $folder/$f
	done
		exit 0
		;;
	"--unpack")
		install $@
	exit 0
		;;
esac

udpkg $@
exit 0
